httprunner/locusts.py

if use api and suite for testcases, locusts will be failed because  the dependencies are not loaded.

fix locusts for test api and suite

---

CHANGELOG.md
httprunner/__about__.py
httprunner/parser.py
httprunner/runner.py
httprunner/utils.py
tests/data/demo_testcase_layer.yml
tests/test_api.py
tests/test_loader.py
tests/testcases/create_user.json
tests/testcases/create_user.v2.json
tests/testcases/create_user.v2.yml
tests/testcases/create_user.yml
tests/testcases/setup.v2.yml
tests/testcases/setup.yml

- feat: 'extract' is used to replace 'output' when passing former teststep's (as a testcase) export value to next teststep
- feat: 'export' is used to replace 'output' in testcase config

2.2.2: rename keyword output

---

httprunner/report.py

对应的 issue ：#707
修复说明：
2.2.6版本的代码，存在多个用例集时，duration计算方法如下：
1.算出各个testcase的start_at
2.**所有testcase结束后计算duration**
3.将各duration累加
可以明显看到，第二步存在问题 
```python
@property      #这里计算的duration周期是错的
def duration(self):
return time.time() - self.start_at
```
修正方式：
多用例集的情况下，直接取结束时间，减去最小开始时间
```python
for key in new_stat:
if key not in origin_stat:
origin_stat[key] = new_stat[key]
elif key == "start_at":
origin_stat[key] = min(origin_stat[key], new_stat[key])
origin_stat["duration"] = time.time() - origin_stat[key]
else:
origin_stat[key] += new_stat[key]
```

修复测试报告duration统计错误

---

httprunner/parser.py

fix: several hooks in the test will be rearranged in the alphabetical order when parsing yaml(json) which will cause the test to be failed.#770

fix: several hooks in the test will be rearranged in the alphabetical order when parsing yaml(json) which will cause the test to be failed.#770

---

httprunner/response.py

```yml
- type_match: [body.data."$ids".id, int]
```
为了支持这种验证路径中有variable的情况
修改前会返回
```json
check_item: body.data."$ids".id
check_value: body.data."2565".id(str)
assert_method: type_match
expect_value: int(str)
```

fix -  get response data with jmespath when variable in validate field

---

httprunner/builtin/comparators.py
tests/utils_test.py

The comparator contained_by assert type on wrong variable `expect_value`.

fix: comparator contained_by should assert the type of expect_vaule.

---

httprunner/client.py

问题描述： response中包含 中文，显示乱码。
版本：3.1.4

解决response的dict中如果包含有汉字，显示转义错误的问题

---

httprunner/client.py
httprunner/loader.py

修改了两个问题：
1. 解析 .env 文件忽略注释和空行 -- [#1117](https://github.com/httprunner/httprunner/issues/1117)
2. 发起请求会解析客户端和服务端的IP地址和端口号并输出日志，当请求协议为 HTTPS 时，解析失败，抛出异常。
以 `examples/httpbin/basic_test.py` 为例，执行后日志如下：
```
2022-01-18 17:49:05.386 | WARNING  | httprunner.client:request:188 - failed to get client address info: 'WrappedSocket' object has no attribute 'getsockname'
2022-01-18 17:49:05.387 | WARNING  | httprunner.client:request:196 - failed to get server address info: 'WrappedSocket' object has no attribute 'getpeername'
```
修改后 HTTPS 也能正常获取。
```
2022-01-18 17:50:55.244 | DEBUG    | httprunner.client:request:188 - client IP: 192.168.xx.xxx, Port: 62608
2022-01-18 17:50:55.244 | DEBUG    | httprunner.client:request:196 - server IP: 54.221.78.73, Port: 443
```

Fixed: 解析 .env 文件忽略注释和空行 && HTTPS 请求获取客户端和服务端 IP 和端口号失败

---

hrp/internal/boomer/boomer.go
hrp/internal/boomer/runner.go
hrp/internal/boomer/runner_test.go

循环次数的定义修改：总循环次数==>每个worker的循环次数。
修改前：测试用例的循环次数=loop-count
修改后：测试用例的循环次数=loop-count * spawn-count
测试：
boom examples/ref_api_test.json --spawn-count 10 --loop-count 100
结果：

fix: modify loop count

---

hrp/internal/builtin/utils.go
hrp/parser.go
hrp/parser_test.go
hrp/response.go

使用GreaterOrEqual做断言时，int与int64类型元素比较会视为不同类型而直接判断为失败
修改：
1. 新增类型标准化函数，在使用parseString函数时标准化int、float等类型，如统一int、int8、int32、int64类型为int64
2. 日志打印新增打印断言类型

fix: failed to assert when int is compared with int64 #1232

---

hrp/step_api.go
hrp/testcase.go

修复在关联参数中使用jmes_path提取参数时，表达式存在连字符而提取失败问题
如：
```
"extract": {
"content_type": "headers.Content-Type"
},
```

fix: deal with extract expr including hyphen

---

.github/workflows/hrp-scaffold.yml
.github/workflows/smoketest.yml
hrp/boomer.go
hrp/runner.go
hrp/summary.go

1. 修改reports报告导出路径逻辑，默认导出至plugin文件所在路径，如果定位失败，则当前运行目录作为兜底路径
2. 增加报告输出路径打印
3. 修复执行压力测试时，extract导出变量未生效而导致关联参数引用失败问题

fix: output html report path optimization and failed to extract variables to session while load testing

---

hrp/internal/boomer/output.go

完善上报至prometheus压测指标数据
新增：
1. 整体压测时长
2. 请求总fail per second
3. 每个请求/事务（总体）：最小响应时间、最小响应时间、总成功数、总失败数

add reporting load testing metrics to prometheus

---

hrp/boomer.go
hrp/parameters.go
hrp/parameters_test.go
hrp/session.go

fix: unsafe to write concurrent map while data driven for testing
问题定位：将参数驱动迭代器中的参数合并到parsedConfig.variables的结果是多goroutine共享的，会存在concurrent map writes问题，因此将参数驱动迭代器中的参数合并到sessionVariables中，效果一致
fix: failed to parse parameters(type:[][]interface{}) in testcase script while data driven for testing
问题定位：
case：
```
"parameters": {
"username-password": [["user1","11111"], ["user2","22222"]]
},
```
error：
```
ERR parameters format error lineIndex=0 parameterNames=["username","password"]
2:28PM ERR parse config parameters failed error="parameters format error" parameters={"user_agent":["iOS/10.1","iOS/10.2"],"username-password":[["user1","11111"],["user2","22222"]]} parametersSetting={"limit":6,"strategies":{"user_agent":"sequential","username-password":"random"}}
2:28PM ERR failed to create …
```

fix: unsafe to write concurrent map and failed to parse parameters(type:[][]interface{}) in testcase script while data driven for testing

---

hrp/boomer.go
hrp/cmd/boom.go
hrp/internal/boomer/boomer.go
hrp/internal/boomer/output.go
hrp/internal/boomer/runner.go
hrp/internal/boomer/stats.go

1. 修复 --disable-keepalive 选项关闭 HTTP 长连接时不能生效的问题
2. 响应时间精确到小数点后三位（毫秒），提升较低循环次数下 RPS 计算结果的准确性
针对同一接口，单个虚拟用户，1秒到达，循环100次。分别使用 HttpRunner 和 JMeter 进行压测：
HttpRunner 结果
JMeter 结果
HttpRunner 结果
JMeter 结果

fix: disable keep alive and improve RPS accuracy

---

hrp/testcase.go

panic原因：测试用例文件中没有config，反序列化后，tc中的config为nil，由对nil指针赋值产生

fix: panic when config didn't exist in testcase file

---

hrp/internal/boomer/ulimit.go

- 修复 #1312 中用户提到的 linux 下 `hrp boom` 设置文件描述符报错 `ERR set ulimit failed error="invalid argument"` 问题
解决方案主要受 [How to set ulimit -n from a golang program?](https://stackoverflow.com/questions/17817204/how-to-set-ulimit-n-from-a-golang-program) 启发，帖子中提到 linux 32 位存在"invalid argument"问题，而 linux 64 位不存在。进而猜测是由于 `SetUlimit` 函数在构建 `syscall.Rlimit` 结构体时只对 Cur 字段赋值，结果导致 Max 字段小于 Cur，引发了"invalid argument"问题。经试验对 Max 字段赋值，并且保证 Max>=Cur 字段后，该问题不再出现，至于"operation not permitted"问题，只需要用户在指令前加上 `sudo` 即可解决

fix: set ulimit error

---

examples/demo-empty-project/proj.json
examples/demo-with-go-plugin/proj.json
examples/demo-with-py-plugin/proj.json
examples/demo-without-plugin/proj.json
hrp/build.go
hrp/internal/scaffold/main.go

修改：保留项目plugin目录下的go.mod，仅在第一次初始化go.mod时go get funplugin@latest，减少go mod init、go get 重复下载带来的不必要耗时

fix: failed to build debugtalk.go without go.mod

---

go.mod
go.sum
hrp/build.go
hrp/internal/builtin/utils.go
hrp/parameters.go

1. 支持自动安装第三方依赖
测试：在debugtalk.py中新增numpy依赖
```
$ hrp run /Users/bytedance/go/src/github.com/httprunner/httprunner/examples/demo-with-py-plugin/testcases/demo.json       
11:06AM INF Set log to color console other than JSON format.
11:06AM ??? Set log level
11:06AM INF [init] SetFailfast failfast=true
11:06AM INF [init] SetSaveTests saveTests=false
11:06AM INF [init] SetRequestsLogOn
11:06AM INF load file path=/Users/bytedance/go/src/github.com/httprunner/httprunner/examples/demo-with-py-plugin/testcases/demo.json
11:06AM INF load file path=/Users/bytedance/go/src/github.com/httprunner/httprunner/examples/demo-with-py-plugin/.env
11:06AM INF set env key=base_url
11:06AM INF set env key=USERNAME
11:06AM INF set env key=PASSWORD
11:06AM INF load testcases successfully count=1
11:06AM INF …
```

fix: ensure all dependencies in debugtalk.go are installed

---

httprunner/make.py

需求背景：项目迭代开发中有些用例无法使用，需要暂时跳过这些不可用的用例
使用示例：
```
config:
name: testcase description
variables: {}
verify: false
parameters:
title-user-pwd:
-   ['ces1', 112, 222]
skip: '跳过原因，可不写， 默认输出无条件跳过'
```
#1153

support skip for pyest

---

hrp/step_api.go
httprunner/runner.py
httprunner/step_testcase.py

fix: panic occurred when the API step failed to run
修复因引用api断言失败而出现panic的问题
fix: step name overrides reference testcase name
修复前
修复后测试用例的name不会被引用的测试用例name所覆盖

fix: panic occurred when the API step failed to run

---

hrp/step_api.go
hrp/testcase.go
httprunner/runner.py
httprunner/step_request.py
httprunner/step_sql_request.py
httprunner/step_testcase.py
httprunner/step_thrift_request.py

1. fix: failed to load json/data content in api reference
问题：当前仅对testcase中的request body做了兼容性处理，如果用户在api中使用json字段来传数据会读取失败
2. fix: ensure complete summary results
问题：每次新创建的sessionRunner实例会共用一个__step_results，使用clear会清理掉之前保存的step_results
测试脚本：
```
from httprunner import HttpRunner, Config, Step, RunTestCase, Parameters, RunRequest
class DemoA(HttpRunner):
url = '/home/pcweb/submit/mancardmenu'
body = {"id": '100'}
config = (
Config("demo")
.base_url('https://www.baidu.com')
)
teststeps = [
Step(
RunRequest("demo")
.post(url)
.with_json(body)
.extract()
.with_jmespath("status_code", 'code')
)
]
class DemoB(HttpRunner):
url = '/home/pcweb/submit/mancardmenu'
body = {"id": '100'}
config = (
Config("demo")
.base_url('https://www.baidu.com')
)
teststeps = [
Step(
RunRequest("demo")
.post(url) …
```

fix: failed to load json/data content in api reference and ensure complete summary results

---

httprunner/config.py

在测试用例config中如果引用参数驱动设置的参数，每次迭代仅能引用到第一个参数
__config中的base_url、variables、name等变量在每次迭代时都不会被重置，使用__parse_config函数解析一次后，后续迭代都将是第一次解析后的参数
Config类新增存未解析的成员变量，在config.struct()函数返回__config前，使用未解析的成员变量对__config进行重置，避免再次迭代时，解析已解析过后的变量而引用参数失败
```
@pytest.mark.parametrize(
"param",
Parameters(
{
"base_url": ["https://www.baidu.com", "https://www.postman_echo.com"]
}
),
)
def test_start(self, param):
super().test_start(param)
config = (
Config("request methods testcase: testcase")
.variables(
**{
"foo1": "testsuite_config_bar1",
"expect_foo1": "testsuite_config_bar1",
"expect_foo2": "config_bar2",
}
)
.base_url("$base_url")
.verify(False)
)
```

fix: reset the testcase config when initializing SessionRunner

---

hrp/plugin.go
hrp/runner_test.go
hrp/step_api.go

当测试用例存在测试用例引用的时候，每跑一次测试用例引用都会新建一个plugin实例，由于实例只能测试结束才能销毁，所以在长时间压测的情况下，会造成系统文件描述符占满、以及内存大量占用问题
修复前：
修复后：
当前在运行时，run api step时会直接修改测试用例的step，出现数据竞争问题

fix: reuse plugin instance if it already initialized

---

docs/CHANGELOG.md
hrp/internal/builtin/function.go
hrp/response.go
hrp/step_api.go
hrp/step_request.go
hrp/testcase.go
hrp/tests/upload_test.go

- fix: 使用 `@FILEPATH` 的固定模式来指定要上传的文件路径
- feat: 上传文件时支持手动指定文件 MIME 类型和名称
- feat: 支持根据文件拓展名自动识别文件 MIME 类型
在用于上传文件的 `upload ` 字段中，当且仅当 map 的值以 @ 开头，例如 `@"FILEPATH"` 或 `@FILEPATH` 的形式时，程序会尝试加载 `FILEPATH ` 所指向的文件，并以 form-data 的形式上传。另外，支持在文件路径的后面增加` filename=xxx `和` type=xxx `选项用于配置 MIME 头域信息，选项和文件路径之间用分号 ‘;‘ 分隔开。
如果 map 值不为文件路径而是普通文本时，程序会自动去除文本最外层包裹的双引号，例如传递的文本为 `"@DUMMYPATH"` 时，实际传递给服务端的是 `@DUMMYPATH`
**注意**
当 map 值为普通文本时，`filename` 和 `type` 选项依然会生效。
下面给出一个完整的测试用例：
```json
{
"config": {
"name": "test upload file to httpbin",
"base_url": "http://httpbin.org",
"variables": {
"upload_file": "test.env"
}
},
"teststeps": [
{
"name": "upload field string with filename and type",
"request": {
"method": "POST",
"url": "/post",
"headers": {
"Content-Type": "${multipart_content_type($m_encoder)}"
}, …
```

feat: add filename/type when uploading form-data

---

httprunner/response.py

目前在debugtalk的自定义方法中，如果需要增加response属性来进行断言判断，不能获取到增加的属性值。这样修改的话，可以在用例断言中，使用自定义的response属性。

support custom requests.Response attr in pytest

---

docs/CHANGELOG.md
hrp/internal/boomer/runner.go

1. 修复未指定压测时间 `--run-time` 时，`hrp boom` 默认只持续最多3s的问题
2. 提升 `--run-time` 到期时间的检测频率（3s 一次改为 1s 一次）

fix: hrp boom --run-time setting

---

hrp/runner.go
hrp/step_android_ui.go
hrp/step_ios_ui.go

支持在android与ios自动化测试用例中l使用$解析udid或serial的引用参数

fix: failed to parse $device_udid in testcase

---

hrp/pkg/uixt/android_adb_driver.go
hrp/runner.go

1. 修复测试用例跑不通过 failfast 时，shell 退出码始终为 1 的问题
2. 修复 adb 驱动，TapFloat 方法 options 未使用的问题

fix: err wrap and TapFloat

---

hrp/step_request.go

只修复了 url 的显示问题，对于 #1468  说的另一个body问题，不归为显示问题。

fix: report html display the value of the url instead of variables

---

docs/CHANGELOG.md
hrp/internal/builtin/utils.go
hrp/pkg/uixt/android_device.go
hrp/pkg/uixt/ios_driver.go
hrp/pkg/uixt/tap.go

- fix: iOS `tap_xy` scale adaption error
- feat: enable uia2 driver if `log_on` is true for android devices

fix: iOS `tap_xy` scale adaption error
