httprunner/httprunner

- HISTORY.md
- httprunner/__about__.py
- httprunner/api.py
- httprunner/client.py
- httprunner/loader.py
- httprunner/runner.py
- httprunner/utils.py
**Bugfixes**
- each teststeps in one testcase share the same session
- fix duplicate API definition output
**Improvements**
- display result from hook functions in DEBUG level log
- change log level of "Variables & Output" to INFO
- print Invalid testcase path or testcases
- print testcase output in INFO level log
> Release 2.0.2

- httprunner/logger.py
- httprunner/utils.py
- tests/debugtalk.py
- tests/test_runner.py
1, dump file with Chinese charactor in Python 3
2, Chinese charactor in log_file encoding error in Windows
> bugfixes with Chinese charactors

- httprunner/parser.py
- tests/data/demo_testcase.yml
- tests/test_api.py
- tests/test_loader.py
- tests/test_parser.py
- tests/testsuites/create_users.yml
bugfix random function in config variables run many times
> bugfix random function in config variables run many times

- HISTORY.md
- Pipfile
- httprunner/__about__.py
- httprunner/built_in.py
- httprunner/loader.py
- httprunner/runner.py
- setup.py
- tests/httpbin/load_image.yml
- tests/httpbin/upload.yml
**Features**
refactor upload files mechanism with [requests-toolbelt](https://toolbelt.readthedocs.io/en/latest/user.html#multipart-form-data-encoder):
- simplify usage syntax, detect mimetype with [filetype](https://github.com/h2non/filetype.py).
- support upload multiple fields.
> 2.1.1 Upload files

- CHANGELOG.md
- Pipfile
- httprunner/__about__.py
- httprunner/loader.py
- tests/test_loader.py
- tests/testcases/setup.json
- tests/testcases/setup.v2.json
- tests/testcases/setup.v2.yml
- tests/testsuites/create_users.json
- tests/testsuites/create_users.v2.json
- tests/testsuites/create_users.v2.yml
support testcase/testsuite in format version 2
> Optimize json testcase format

- examples/postman_echo/request_methods/demo_testsuite_yml/request_with_functions_test.py
- examples/postman_echo/request_methods/demo_testsuite_yml/request_with_testcase_reference_test.py
- httprunner/compat.py
- httprunner/ext/har2case/utils.py
- httprunner/make.py
- tests/compat_test.py
- fix: ensure variables
- fix: handle exception for loaded invalid format test content
- change: do not capture exception for loading har file
> 3.0.9 bugfix

- examples/postman_echo/debugtalk.py
- examples/postman_echo/request_methods/account.csv
- examples/postman_echo/request_methods/request_with_parameters.yml
- httprunner/make.py
- httprunner/models.py
- httprunner/parser.py
- httprunner/runner.py
- httprunner/utils.py
- tests/account.csv
- tests/make_test.py
- tests/parser_test.py
- tests/utils_test.py
closes #931, #929
**add**
New feature: config part support "parameters". example: examples\postman_echo\request_methods\request_with_parameters.yml
> Issue/#931 add new feature "paramters"

- docs/CHANGELOG.md
- httprunner/__init__.py
- poetry.lock
- pyproject.toml
add brotli dependency to support decoding brotli
> fix: decode brotli encoding

- .github/workflows/hrp-scaffold.yml
- .github/workflows/smoketest.yml
- .github/workflows/unittest.yml
- docs/CHANGELOG.md
- hrp/boomer.go
- hrp/convert.go
- hrp/convert_test.go
- hrp/internal/builtin/utils.go
- hrp/models.go
- hrp/runner.go
- hrp/runner_test.go
- hrp/step.go
- feat: support run testcases in specified folder path
- refactor: simplify models
> feat: support run testcases in specified folder path

- docs/CHANGELOG.md
- hrp/runner.go
- hrp/runner_test.go
- httprunner/utils.py
feat: support run testcases in specified folder path, including testcases in sub folders
> feat: support run testcases in specified folder path, including testcases in sub folders

- httprunner/utils.py
> fix: annotation-wrong

- hrp/boomer.go
问题：压测时，copy的测试用例配置解析后未被使用
修改：直接使用拷贝过后的测试用例创建sessionRunner
> fix: failed to parse testcase config while load testing

- hrp/response.go
- hrp/response_test.go
- hrp/tests/request_test.go
feat: parse check item before jmespath search
> feat: parse check item before jmespath search

- hrp/step_testcase.go
> fix: add ref step name info in html report

- build/Dockerfile
> feat: add dockerfile

- hrp/boomer.go
- hrp/plugin.go
- hrp/runner.go
> fix: quit plugin

- hrp/boomer.go
- hrp/internal/boomer/boomer.go
- hrp/internal/boomer/client_grpc.go
- hrp/internal/boomer/message.go
- hrp/internal/boomer/output.go
- hrp/internal/boomer/runner.go
- hrp/internal/boomer/runner_test.go
- hrp/internal/boomer/server_grpc.go
- hrp/plugin.go
- hrp/runner.go
- hrp/runner_test.go
- hrp/server.go
- hrp/step_request.go
- hrp/testcase.go
> fix: state machine

- examples/uitest/demo_douyin_follow_live.json
- examples/uitest/demo_douyin_follow_live.yaml
- examples/uitest/demo_douyin_follow_live_test.go
- hrp/pkg/uixt/android_driver.go
- hrp/pkg/uixt/ext.go
- hrp/pkg/uixt/ocr_off.go
- hrp/pkg/uixt/ocr_on.go
- hrp/pkg/uixt/swipe.go
- hrp/pkg/uixt/tap.go
- hrp/step.go
- hrp/step_android_ui.go
- hrp/step_ios_ui.go
```
testCase := &hrp.TestCase{
Config: hrp.NewConfig("通过 关注天窗 进入指定主播抖音直播间").
WithVariables(map[string]interface{}{
"app_name": "抖音",
}).
SetIOS(
hrp.WithLogOn(true),
hrp.WithWDAPort(8100),
hrp.WithWDAMjpegPort(9100),
),
TestSteps: []hrp.IStep{
hrp.NewStep("启动抖音").
IOS().
Home().
AppTerminate("com.ss.iphone.ugc.Aweme"). // 关闭已运行的抖音
SwipeToTapApp("$app_name", hrp.WithMaxRetryTimes(5), hrp.WithIdentifier("启动抖音")).Sleep(5).
Validate().
AssertOCRExists("推荐", "抖音启动失败，「推荐」不存在"),
hrp.NewStep("处理青少年弹窗").
IOS().
TapByOCR("我知道了", hrp.WithIgnoreNotFoundError(true)),
hrp.NewStep("点击首页").
IOS().
TapByOCR("首页", hrp.WithIndex(-1)).Sleep(10),
hrp.NewStep("点击关注页").
IOS().
TapByOCR("关注", hrp.WithIndex(1)).Sleep(10),
hrp.NewStep("向上滑动 2 次").
IOS().SwipeToTapFromTexts([]string{"理肤泉", "婉宝"}, …
```
> feat: tap the first one matches text from given texts by ocr

- hrp/boomer.go
- hrp/runner.go
> fix: fast fail , not closing the websocket connection

- docs/CHANGELOG.md
- hrp/runner.go
- hrp/step_mobile_ui.go
- feat: support parsing expect value of ui validator
> feat: support parsing expect value of ui validator

- examples/uitest/android_expert_test.json
- examples/uitest/expert_test.go
- examples/uitest/ios_expert_test.json
- hrp/pkg/uixt/action.go
- hrp/pkg/uixt/service_vedem.go
- hrp/pkg/uixt/tap.go
- hrp/step_mobile_ui.go
- introduce expert test for both integration and regression
- add `TapByUITypes` method in step_mobile_ui.go
> introduce expert test for both integration and regression

- hrp/pkg/uixt/action.go
- hrp/pkg/uixt/service_vedem.go
- hrp/pkg/uixt/swipe.go
- fix: add option match_one for FindTexts method
> fix: add option match_one for FindTexts method

- docs/CHANGELOG.md
- examples/uitest/android_expert_test.json
- examples/uitest/expert_test.go
- examples/uitest/ios_expert_test.json
- hrp/pkg/uixt/action.go
- hrp/pkg/uixt/ext.go
- hrp/pkg/uixt/interface.go
- hrp/pkg/uixt/ios_driver.go
- hrp/pkg/uixt/popups.go
- hrp/pkg/uixt/service_vedem.go
- hrp/pkg/uixt/service_vedem_test.go
- hrp/pkg/uixt/swipe.go
- hrp/pkg/uixt/tap.go
- hrp/pkg/uixt/video_crawler.go
- hrp/step_mobile_ui.go
- feat: support new action: close_popups
> feat: support new action: close_popups

- hrp/internal/builtin/utils.go
- hrp/pkg/uixt/action.go
- hrp/pkg/uixt/ext.go
- hrp/pkg/uixt/interface.go
- hrp/pkg/uixt/popups.go
- hrp/pkg/uixt/service_vedem.go
- hrp/testcase.go
- add popup close_status=found
- compatible with old tap_cv params
> add popup close_status=found

- hrp/testcase.go
- set default max_retry_times for swipe_to_tap_text
> set default max_retry_times for swipe_to_tap_text

- hrp/pkg/uixt/swipe.go
- fix: swipeToTapTexts redundant identifiers
> fix: swipeToTapTexts redundant identifiers
